# Generated by Django 6.0.5 on 2026-05-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('servico_contratado', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('nota', models.CharField(choices=[('1', '1 estrela'), ('2', '2 estrelas'), ('3', '3 estrelas'), ('4', '4 estrelas'), ('5', '5 estrelas')], max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
