# Generated by Django 6.0.5 on 2026-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_servico_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizacaoHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Agenda Fácil', max_length=100)),
                ('subtitulo', models.CharField(default='Agende serviços de forma simples, rápida e organizada.', max_length=255)),
                ('exibir_titulo_subtitulo', models.BooleanField(default=True)),
                ('cor_header', models.CharField(default='#6b7b4b', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header_logos/')),
            ],
        ),
    ]
