# Generated by Django 6.0.5 on 2026-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_customizacaoheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizacaoheader',
            name='logo_posicao',
            field=models.CharField(choices=[('esquerda', 'Esquerda'), ('centro', 'Centro')], default='esquerda', max_length=10),
        ),
        migrations.AlterField(
            model_name='customizacaoheader',
            name='subtitulo',
            field=models.CharField(blank=True, default='Agende serviços de forma simples, rápida e organizada.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customizacaoheader',
            name='titulo',
            field=models.CharField(blank=True, default='Agenda Fácil', max_length=100),
        ),
    ]
